# fly.toml file for fabsoft-backend

app = "fabsoft-backend"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

# Secção de verificação de saúde que acabámos de adicionar
[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  tls_skip_verify = false
  [http_service.checks.headers]